//
// Created by minau on 12/14/2022.
//

#ifndef SFML_PROJECT_PROJECTDEFINITIONS_H
#define SFML_PROJECT_PROJECTDEFINITIONS_H

#define PORTFOLIO_SCREEN_WIDTH 950
#define PORTFOLIO_SCREEN_HEIGHT 950

#endif //SFML_PROJECT_PROJECTDEFINITIONS_H
